networks:
  proxy:
    driver: bridge

services:
  database-encurtador:
    image: postgres:17.0
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=GMT-3
    networks:
      - proxy
    volumes:
      - ./database_encurtador_volume/:/var/lib/postgresql/data

  api:
    build: ./
    restart: always
    env_file: .env
    depends_on: 
      - database-encurtador
    environment:
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_KEY: ${JWT_KEY}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      BASE_URL: ${BASE_URL}
      TZ: America/Sao_Paulo
      API_PORT: ${API_PORT}
    ports:
      - 3333:3333
    expose:
      - 3333
    networks:
      - proxy

volumes:
  database_encurtador_volume:
