services:
  database-encurtador:
    image: postgres:17.0
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database_encurtador_volume/:/var/lib/postgresql/data

volumes:
  database_encurtador_volume:
